query getConfigs @api(name: "ai") {
  getConfigs @rest(type: "Config", path: "/config", method: "GET", endpoint: "ai") {
    id
    key
    value
    key_type
    is_secret
    is_required
    agent_id
    tool_id
    datasource_id
    account_id
    project_id
    is_deleted
    created_by
    modified_by
  }
}
