#import "./configFragment.gql"

mutation createConfig($input: input!) @api(name: ai) {
  createConfig(input: $input)
    @rest(type: "Config", path: "/config", method: "POST", bodyKey: "input", endpoint: "ai") {
    ...ConfigFragment
  }
}
