#import "./configFragment.gql"

mutation updateConfig($id: id!, $input: input!) @api(name: "ai") {
  updateConfig(id: $id, input: $input)
    @rest(type: "Config", path: "/config/{args.id}", method: "PUT", endpoint: "ai") {
    ...ConfigFragment
  }
}
