mutation createTeamOfAgents($input: input!) @api(name: ai) {
  createTeamOfAgents(input: $input)
    @rest(
      type: "TeamOfAgents"
      path: "/team"
      method: "POST"
      bodyKey: "input"
      endpoint: "ai"
    ) {
    id
    name
    description
    team_type
    workspace_id
    is_deleted
    is_template
    is_public
    account_id
    created_by
    modified_by
  }
}
