mutation deleteTeamOfAgents($id: id!) @api(name: ai) {
  deleteTeamOfAgents(id: $id)
    @rest(
      type: "TeamOfAgents"
      path: "/team/{args.id}"
      method: "DELETE"
      bodyKey: "input"
      endpoint: "ai"
    ) {
    agent
  }
}
