#import "./teamOfAgentFragment.gql"

query getTeamOfAgentsPublic @api(name: "ai") {
  getTeamOfAgentsPublic
    @rest(type: "TeamOfAgents", path: "/team/discover/public", method: "GET", endpoint: "ai") {
    ...TeamOfAgentFragment
  }
}
