#import "./teamOfAgentFragment.gql"

query teamOfAgentsById($id: id!) @api(name: "ai") {
  teamOfAgentsById(id: $id)
    @rest(type: "TeamOfAgents", path: "/team/{args.id}", method: "GET", endpoint: "ai") {
    ...TeamOfAgentFragment
  }
}
