query getTeamTypes @api(name: "ai") {
  getTeamTypes @rest(type: "TeamTypes", path: "/team/types", method: "GET", endpoint: "ai") {
    is_active
    name
    description
    team_type
    agents {
      id
      role
    }
    fields
  }
}
