fragment TeamOfAgentFragment on TeamOfAgents {
  id
  name
  description
  team_type
  workspace_id
  is_deleted
  is_public
  account_id
  created_by
  avatar
  creator {
    id
    name
    email
    avatar
  }
  modified_by
  team_agents {
    id
    role
    agent
  }
  configs
}
