#import "./teamOfAgentFragment.gql"

query getTeamOfAgents @api(name: "ai") {
  getTeamOfAgents @rest(type: "TeamOfAgents", path: "/team", method: "GET", endpoint: "ai") {
    ...TeamOfAgentFragment
  }
}
