query teamOfAgentsById($id: id!) @api(name: "ai") {
  teamOfAgentsById(id: $id)
    @rest(type: "TeamOfAgents", path: "/team-of-agents/{args.id}", method: "GET", endpoint: "ai") {
    id
    name
    description
    team_type
    workspace_id
    is_deleted
    is_system
    account_id
    created_by
    modified_by
  }
}
