query getTeamTypes @api(name: "ai") {
  getTeamTypes
    @rest(type: "TeamTypes", path: "/team-of-agents/types", method: "GET", endpoint: "ai") {
    is_active
    name
    description
    team_type
  }
}
