export const FILE_TYPES = [
  'application/pdf',
  'text/csv',
  'application/msword',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'text/markdown',
  'image/jpeg',
  'image/png',
  'application/epub+zip',
  'application/mbox',
  'application/x-ipynb+json',
  'audio/mpeg',
  'video/mp4',
  'text/plain',
]

export const SUPPORTED_FILE_EXTENSIONS = [
  'txt',
  'pdf',
  'csv',
  'json',
  'docx',
  'pptx',
  'md',
  'jpg',
  'png',
  'jpeg',
  'epub',
  'mbox',
  'ipynb',
  'mp3',
  'mp4',
]
