query getMarketplaceAgents @api(name: "ai") {
  getMarketplaceAgents
    @rest(type: "Agent", path: "/agent/marketplace", method: "GET", endpoint: "ai") {
    templateAgents {
      agent
      configs
    }
    systemAgents {
      agent
      configs
    }
  }
}
