mutation createGroup($input: input!) @api(name: ai) {
  createGroup(input: $input)
    @rest(type: "Group", path: "/group", method: "POST", bodyKey: "input", endpoint: "ai") {
    id
    name
    description
  }
}
