# Use the Python 3.11 base image
FROM python:3.11

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install dependencies
COPY pyproject.toml poetry.lock /app/

RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

# Copy project
COPY ./ /app/

# Run Celery worker
ENTRYPOINT ["celery", "-A", "main", "worker", "--loglevel=info"]
