mutation githubLogin($body: JSON!)  @api(name: account) {
  githubLogin: publish(body: $body) @rest(
      type: "Post"
      path: "/auth/github-login"
      method: "POST"
      bodyKey: "body",
      endpoint: "account"
    ) {
      auth_url
  }
}
