mutation resetPassword($body: JSON!) @api(name: account) {
  resetPassword: publish(body: $body)
    @rest(
      type: "Post"
      path: "/auth/reset-password"
      method: "POST"
      bodyKey: "body"
      endpoint: "account"
    ) {
    success
    message
  }
}
