#import "./dataSourceFragment.gql"

mutation createDatasource($input: input!) @api(name: ai) {
  createDatasource(input: $input)
    @rest(
      type: "Datasource"
      path: "/datasource"
      method: "POST"
      bodyKey: "input"
      endpoint: "ai"
    ) {
    ...DataSourceFragment
  }
}
