query getDataLoaders @api(name: "ai") {
  getDataLoaders
    @rest(type: "Datasource", path: "/datasource/data-loaders", method: "GET", endpoint: "ai") {
    is_active
    name
    category
    source_type
    fields {
      label
      key
      type
      is_secret
      is_required
    }
  }
}
