#import "./dataSourceFragment.gql"

query datasourceById($id: id!) @api(name: "ai") {
  datasourceById(id: $id)
    @rest(type: "Datasource", path: "/datasource/{args.id}", method: "GET", endpoint: "ai") {
    ...DataSourceFragment
  }
}
