query getDatasourceSqlTables(
  $source_type: String
  $host: String
  $port: Int
  $user: String
  $password: String
  $name: String
  $id: String
) @api(name: "ai") {
  getDatasourceSqlTables(
    source_type: $source_type
    host: $host
    port: $port
    user: $user
    password: $password
    name: $name
    id: $id
  ) @rest(type: "String", path: "/datasource/sql/tables?{args}", method: "GET", endpoint: "ai") {
    id
    name
    count
  }
}
