#import "./dataSourceFragment.gql"

mutation updateDatasource($id: id!, $input: input!) @api(name: "ai") {
  updateDatasource(id: $id, input: $input)
    @rest(type: "Datasource", path: "/datasource/{args.id}", method: "PUT", endpoint: "ai") {
    ...DataSourceFragment
  }
}
