query models @api(name: "ai") {
  models @rest(type: "Model", path: "/model", method: "GET", endpoint: "ai") {
    id
    provider
    name
    value
    fine_tuning
    is_fine_tuned
    is_voice
  }
}
