fragment GameFields on Game {
  id
  name
  category
  description
  created_on
  modified_on
  created_by
  modified_by
  account_id
  banner_image
  logo_image
  background_image
  url
  web_link
  discord
  twitter
  instagram
  status
  contact_email
  contact_phone
  is_url
  medias
  main_media
  social_links
}
