query getFineTunings @api(name: "ai") {
  getFineTunings @rest(type: "FineTuning", path: "/fine-tuning", method: "GET", endpoint: "ai") {
    id
    name
    file_url
    identifier
    status
    model_id
  }
}
