query apiKeyById($id: id!) @api(name: "ai") {
  apiKeyById(id: $id)
    @rest(type: "ApiKeys", path: "/api-key/{args.id}", method: "GET", endpoint: "ai") {
    id
    name
    token
    description
    is_deleted
    account_id
    created_on
    created_by
    modified_by
  }
}
