mutation deleteApiKey($id: id!) @api(name: ai) {
  deleteApiKey(id: $id)
    @rest(
      type: "ApiKeys"
      path: "/api-key/{args.id}"
      method: "DELETE"
      bodyKey: "input"
      endpoint: "ai"
    ) {
    agent
  }
}
