mutation updateApiKey($id: ID!, $input: ApiKeyInput!) @api(name: game) {
  updateApiKey(id: $id, input: $input) {
    success
    apiKey {
      id
      name
      token
      note
      expiration
      games
      created_on
      last_used
    }
  }
}
