query chatMessages($is_private_chat: Boolean!, $agent_id: String!, $team_id: String!)
@api(name: "ai") {
  chatMessages(is_private_chat: $is_private_chat, agent_id: $agent_id, team_id: $team_id)
    @rest(type: "ChatMessage", path: "/chat?{args}", method: "GET", endpoint: "ai") {
    id
    session_id
    user_id
    account_id
    message
    thoughts
    created_on
    parent
    parent_id
    agent_id
    agent
    team_id
    team
    creator
  }
}
