mutation createClientChatMessage($input: input!) @api(name: ai) {
  createClientChatMessage: publish(input: $input)
    @rest(
      type: "ChatMessage"
      path: "/chat/session/messages"
      method: "POST"
      bodyKey: "input"
      endpoint: "ai"
    )
}
