query MessageByGame($is_private_chat: Boolean!, $version: String!) @api(name: "ai") {
  messageByGame(is_private_chat: $is_private_chat, version: $version)
    @rest(type: "ChatMessage", path: "/chat?{args}", method: "GET", endpoint: "ai") {
    id
    session_id
    user_id
    account_id
    message
    thoughts
    version
    created_on
    parent
    parent_id
  }
}
