mutation stopChat($input: input!) @api(name: ai) {
  stopChat: publish(input: $input)
    @rest(type: "Config", path: "/chat/stop", method: "POST", bodyKey: "input", endpoint: "ai") {
    id
    key
    value
    key_type
    is_secret
    is_required
    agent_id
    toolkit_id
    datasource_id
    team_id
    account_id
    workspace_id
    is_deleted
    created_by
    modified_by
  }
}
