query campaignById($id: id!) @api(name: "pro") {
  campaignById(id: $id)
    @rest(type: "Campaign", path: "/v1/campaign/{args.id}", method: "GET", endpoint: "pro") {
    id
    name
    group_id
    agent_id
    type
    start_date
    status
    retry_attempts
    retry_interval
    working_hours_start
    working_hours_end
    timezone
  }
}
