query getCampaigns @api(name: "pro") {
  getCampaigns @rest(type: "Campaign", path: "/v1/campaign", method: "GET", endpoint: "pro") {
    id
    name
    group_id
    agent_id
    type
    start_date
    status
    total_calls
    call_statuses
    retry_attempts
    retry_interval
    working_hours_start
    working_hours_end
    timezone
  }
}
