mutation createCampaign($input: input!) @api(name: pro) {
  createCampaign(input: $input)
    @rest(
      type: "Campaign"
      path: "/v1/campaign"
      method: "POST"
      bodyKey: "input"
      endpoint: "pro"
    ) {
    name
    agent_id
    group_id
    start_date
    type
  }
}
