mutation updateSchedule($id: id!, $input: input!) @api(name: "ai") {
  updateSchedule(id: $id, input: $input)
    @rest(type: "schedule", path: "/schedule/{args.id}", method: "PUT", endpoint: "ai") {
    schedule {
      id
      is_active
      name
      schedule_type
      description
      max_daily_budget
      cron_expression
    }
    configs {
      agent_id
      group_id
    }
  }
}
