"""pod resource relation

Revision ID: f9036e174244
Revises: ff6d7055ccb3
Create Date: 2024-06-06 13:51:48.084697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9036e174244'
down_revision: Union[str, None] = 'ff6d7055ccb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pod', sa.Column('resource', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_pod_resource'), 'pod', ['resource'], unique=False)
    op.create_foreign_key(None, 'pod', 'resource', ['resource'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pod', type_='foreignkey')
    op.drop_index(op.f('ix_pod_resource'), table_name='pod')
    op.drop_column('pod', 'resource')
    # ### end Alembic commands ###
